// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xeeihcyeubeupadknqla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlZWloY3lldWJldXBhZGtucWxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NzMzNjYsImV4cCI6MjA2MzU0OTM2Nn0.5sF2mS7aBDqjRyn6uymgrszUMnAX_bYWF2BTtESa6MI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);